---
title: 'p8105_hw2_jc6693'
author: 'Jingfeng Cao'
output: github_document
---

## Problem 1

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

import data pols_month
```{r}
pols_month_df = read_csv('fivethirtyeight_datasets/pols-month.csv') |>
  janitor::clean_names() |>
  separate(mon,into = c('year','month','day'),sep = '-') |>
  mutate(year = as.integer(year), month = as.integer(month), day = as.integer(day)) |>
  mutate(month = lubridate::month(month,label = TRUE, abbr = FALSE)) |>
  mutate(president = case_when(prez_dem == 1 ~ 'dem', prez_gop == 1 ~ 'gop')) |>
  select(-prez_dem, -prez_gop, -day)
```

import data snp
```{r}
snp_df = read_csv('fivethirtyeight_datasets/snp.csv') |>
  janitor::clean_names() |>
  separate(date,into = c('month','day','year'),sep = '/') |>
  mutate(year = as.integer(year), month = as.integer(month), day = as.integer(day)) |>
  mutate(year = case_when(year <= 25 ~ year+2000, year >= 26 ~ year+1900)) |>
  arrange(year,month) |>
  mutate(month = lubridate::month(month,label = TRUE, abbr = FALSE)) |>
  select(year,month, everything(), -day)
```

import data unemployment




